# Generated by Django 2.2.7 on 2020-03-26 12:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiVanBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_van_ban', models.CharField(max_length=255)),
                ('thu_tu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VanBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_file', models.CharField(max_length=10)),
                ('kich_thuoc', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('so_lan_download', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('diem', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('xem', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngay_dang', models.DateTimeField()),
                ('file_upload', models.FileField(upload_to='documents/')),
                ('loai_van_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vanban.LoaiVanBan')),
            ],
        ),
    ]
