# Generated by Django 2.2.7 on 2020-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanban',
            name='tieu_de',
            field=models.CharField(default='Nhập tiêu đề', max_length=255),
            preserve_default=False,
        ),
    ]
