# Generated by Django 2.2.7 on 2020-03-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vanban', '0002_vanban_tieu_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanban',
            name='kich_thuoc',
        ),
        migrations.RemoveField(
            model_name='vanban',
            name='loai_file',
        ),
    ]
