# Generated by Django 2.2.7 on 2020-03-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanban', '0003_auto_20200327_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanban',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
