# Generated by Django 2.2.7 on 2020-02-10 07:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='noi_dung',
            field=tinymce.models.HTMLField(),
        ),
    ]
