# Generated by Django 2.2.7 on 2020-03-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0002_auto_20200305_1945'),
        ('tintuc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_tin_tuc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tintuc',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trangchu.Menu'),
        ),
    ]
