# Generated by Django 2.2.7 on 2020-03-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0002_auto_20200305_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoaiTinTuc',
        ),
        migrations.AddField(
            model_name='tintuc',
            name='tin_noi_bat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
