# Generated by Django 2.2.7 on 2020-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0003_auto_20200210_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='mo_ta_ngan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tintuc',
            name='noi_dung',
            field=models.TextField(),
        ),
    ]
