# Generated by Django 2.2.7 on 2020-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0003_auto_20200325_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='tin_noi_bat',
            field=models.BooleanField(default=False),
        ),
    ]
