# Generated by Django 2.2.7 on 2020-02-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0004_auto_20200211_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_tin_tuc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tintuc',
            name='loai_tin_tuc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tintuc.LoaiTinTuc'),
        ),
    ]
