# Generated by Django 2.2.7 on 2020-02-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tintuc', '0005_auto_20200212_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tintuc',
            old_name='tien_de',
            new_name='tieu_de',
        ),
    ]
