# Generated by Django 2.2.7 on 2020-03-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0002_auto_20200228_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
