# Generated by Django 2.2.7 on 2020-04-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('danh_muc', models.PositiveSmallIntegerField()),
                ('noi_dung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TraLoi',
            fields=[
                ('cau_hoi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hoidap.CauHoi')),
                ('dap_an', models.TextField()),
            ],
        ),
    ]
